juan/CP06-login
florencialecha/digital-bank-qa-automation pull request #10
Opened 2023-05-23 12:17 UTC by JISaldana

This test verifies the correct functioning of the "Remember Me" box

2023-05-23 12:32 UTC, sofiambd requested changes
Revisar comentarios.

2023-05-23 12:32 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/loginTests/shouldNotLoginWhenWrongPasswordIsProvided.java
> +        //Assert wrong credentials alert on login page
Usar steps en pages, no es necesario comentarios.

2023-05-23 12:32 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/loginTests/shouldNotLoginWhenWrongPasswordIsProvided.java
> +        Assert.assertEquals(cantLoginAlert, "Error Invalid credentials or access not granted due to user account status or an existing user session.\n" + "×");
Para strings, es buena practica definirla en el codigo y llamarla.

2023-05-23 12:32 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/loginTests/shouldRembemberLastLogedUsernameWhenRememberMeCheckboxIsCheck.java
> +        Assert.assertEquals(currentUrl, "http://digitalbank.upcamp.io/bank/home");
Mismo comentario que strings.

2023-05-23 12:32 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/loginTests/shouldRembemberLastLogedUsernameWhenRememberMeCheckboxIsCheck.java
> +        //Assert login
Evitar comentarios, con steps en las pages es suficiente.

2023-05-23 12:32 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/pages/HeaderPage.java
> +        public HomePage clickDeleteDataButton() {
Falta Step

2023-05-23 12:32 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/pages/HeaderPage.java
> +        public void clickUserProfileBtn() {
Falta Step

2023-05-24 16:19 UTC, sofiambd submitted a review, later dismissed

2023-05-24 16:21 UTC, florencialecha approved these changes

2023-05-24 16:23 UTC, merged