Florencia/cp000 my profile
florencialecha/digital-bank-qa-automation pull request #5
Opened 2023-05-19 13:17 UTC by florencialecha

- Process to create AccountDeletionTest:
- Modify Newchecking Page to add newCheckingBtn 
- Add testng suitefile and create newCheckingSuite.xml
- Create Data Provider Account Data
- Add balanceAccountCheck
- Clean Allure Reports

Extra:
- Fix class SingleAccountActivationTest add teardown

2023-05-19 17:53 UTC, JISaldana approved these changes, later dismissed

2023-05-19 17:53 UTC, JISaldana commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/myProfile/AccountDeletionTest.java
> +        //El login me debería llevar a una home que tiene una sidebar y una header page
translate this so all comments are in the same language

2023-05-19 17:53 UTC, JISaldana commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/viewChecking/AccountExistViewTest.java
> +        //Pasarle usuario con cuentas de checking existentes
translate this too

2023-05-23 12:38 UTC, sofiambd requested changes
Tratar de mantener los PR lo más pequeños posibles, como dijimos en la working session de Buenas practicas, deberia ser 1 PR por test.

2023-05-23 12:38 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/myProfile/AccountDeletionTest.java
> +        // Check redirection to home
Tratar de no usar comentarios, con Steps en pages es suficientes.

2023-05-23 12:38 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/myProfile/AccountDeletionTest.java
> +        Assert.assertEquals(currentUrl, "http://digitalbank.upcamp.io/bank/home");
es buena practica Strings definirlas y usarlas en codigo, no "quemar" el texto

2023-05-23 12:38 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/newChecking/NewCheckingAccountCreation.java
> +        // Log in with a user
Revisar comentarios primer test

2023-05-23 12:38 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/viewChecking/AccountExistViewTest.java
> +        //Pasarle usuario con cuentas de checking existentes
Revisar comentarios primer test

2023-05-23 12:38 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/viewChecking/SingleAccountActivationTest.java
> +        // Verify that the first account is deactivated
Revisar comentarios primer test.

2023-05-23 12:38 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/pages/HeaderPage.java
> +    public HomePage clickDeleteDataButton() {
Faltan Steps

2023-05-24 17:06 UTC, closed without merging