Florencia/vch16 view checking - Add test AccountExistViewTest
florencialecha/digital-bank-qa-automation pull request #6
Opened 2023-05-19 13:44 UTC by florencialecha

Add test shouldDisplayCheckingViewPageWhenAccountsExist() for AccountExistViewTest:
When a user with checking accounts views their checking accounts, account cards and transaction history should be displayed. 

Note: this test need to add a first step where create a new checking account and a finally step where delete data account. I'm going to add that on the next pr.

2023-05-19 17:39 UTC, JISaldana approved these changes, later dismissed

2023-05-23 12:54 UTC, sofiambd requested changes

2023-05-23 12:54 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/viewChecking/SingleAccountActivationTest.java
> +        // Log in with a user with multiple checking accounts
No es necesario comentarios si estan los steps en las pages.

2023-05-23 12:54 UTC, sofiambd commented on qa-automation/src/test/java/com/digitalbank/qaautomation/tests/viewChecking/SingleAccountActivationTest.java
> +        Assert.assertTrue(isFirstAccountActive, "The first account should be active after activation");
Definir Strings

2023-05-23 15:07 UTC, JISaldana approved these changes

2023-05-23 16:16 UTC, sofiambd approved these changes

2023-05-23 16:48 UTC, closed without merging